// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGck_xlNhaJ0bkqkzi0eOv5sVaHe6VVhQ',
    appId: '1:119777053641:web:fa39d08fc541a29810f618',
    messagingSenderId: '119777053641',
    projectId: 'dndadventure-59102',
    authDomain: 'dndadventure-59102.firebaseapp.com',
    storageBucket: 'dndadventure-59102.appspot.com',
    measurementId: 'G-SRB3KTNXT9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp8S8reNPHVGvg9_4jXneoAZ1kkqyCDQo',
    appId: '1:119777053641:android:2b47f48c546525ec10f618',
    messagingSenderId: '119777053641',
    projectId: 'dndadventure-59102',
    storageBucket: 'dndadventure-59102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAufa9BBibOgszl8ZRJCRxFeXgx6Rl-MAQ',
    appId: '1:119777053641:ios:41e1fe7f2862352c10f618',
    messagingSenderId: '119777053641',
    projectId: 'dndadventure-59102',
    storageBucket: 'dndadventure-59102.appspot.com',
    iosBundleId: 'com.example.dndAdventure',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAufa9BBibOgszl8ZRJCRxFeXgx6Rl-MAQ',
    appId: '1:119777053641:ios:93102820226c655710f618',
    messagingSenderId: '119777053641',
    projectId: 'dndadventure-59102',
    storageBucket: 'dndadventure-59102.appspot.com',
    iosBundleId: 'com.example.dndAdventure.RunnerTests',
  );
}
